In [1]:
# Pythia 70M - check SAEs from Sam Marks

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from linearization.analyzer import SAELinearizer

In [23]:
lin = SAELinearizer(
    model_name="pythia-70m",
    sae_names=[f"{x}/0_8192" for x in [0, 1, 2, 3, 4, 5]],
    layers=[0, 1, 2, 3, 4, 5],
    dataset_name="NeelNanda/pile-10k",
    act_name="mlp_out",
    num_batches=50,
    run_analysis=False,
)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Loaded pretrained model pythia-70m into HookedTransformer
Moving model to device:  cuda
Changing model dtype to torch.float16
Model device: cuda:0
Tokens shape: torch.Size([120866, 128]), dtype: torch.int64, device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0


In [5]:
out, cache = lin.model.run_with_cache(lin.data[0])
cache.keys()

dict_keys(['hook_embed', 'blocks.0.hook_resid_pre', 'blocks.0.ln1.hook_scale', 'blocks.0.ln1.hook_normalized', 'blocks.0.attn.hook_q', 'blocks.0.attn.hook_k', 'blocks.0.attn.hook_v', 'blocks.0.attn.hook_rot_q', 'blocks.0.attn.hook_rot_k', 'blocks.0.attn.hook_attn_scores', 'blocks.0.attn.hook_pattern', 'blocks.0.attn.hook_z', 'blocks.0.hook_attn_out', 'blocks.0.ln2.hook_scale', 'blocks.0.ln2.hook_normalized', 'blocks.0.mlp.hook_pre', 'blocks.0.mlp.hook_post', 'blocks.0.hook_mlp_out', 'blocks.0.hook_resid_post', 'blocks.1.hook_resid_pre', 'blocks.1.ln1.hook_scale', 'blocks.1.ln1.hook_normalized', 'blocks.1.attn.hook_q', 'blocks.1.attn.hook_k', 'blocks.1.attn.hook_v', 'blocks.1.attn.hook_rot_q', 'blocks.1.attn.hook_rot_k', 'blocks.1.attn.hook_attn_scores', 'blocks.1.attn.hook_pattern', 'blocks.1.attn.hook_z', 'blocks.1.hook_attn_out', 'blocks.1.ln2.hook_scale', 'blocks.1.ln2.hook_normalized', 'blocks.1.mlp.hook_pre', 'blocks.1.mlp.hook_post', 'blocks.1.hook_mlp_out', 'blocks.1.hook_resid_

In [18]:
from linearization.sae_tutorial import get_freqs

get_freqs(
    all_tokens=lin.data, model=lin.model, act_name="mlp_out", layer=0, num_batches=5, local_encoder=lin.saes["0/0_8192"]
)

get_freqs


100%|██████████| 5/5 [00:00<00:00, 77.46it/s]

Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Num dead 0.0


tensor([0.3018, 0.0674, 0.0920,  ..., 0.0238, 0.0465, 0.1105], device='cuda:0')

In [22]:
from linearization.analyses.model import frequencies, f1_scores

frequencies(model=lin.model, sae=lin.saes["0/0_8192"], data=lin.data, layer=0, num_batches=5, act_name="mlp_out")

model: HookedTransformer(
  (embed): Embed()
  (hook_embed): HookPoint()
  (blocks): ModuleList(
    (0-5): 6 x TransformerBlock(
      (ln1): LayerNormPre(
        (hook_scale): HookPoint()
        (hook_normalized): HookPoint()
      )
      (ln2): LayerNormPre(
        (hook_scale): HookPoint()
        (hook_normalized): HookPoint()
      )
      (attn): Attention(
        (hook_k): HookPoint()
        (hook_q): HookPoint()
        (hook_v): HookPoint()
        (hook_z): HookPoint()
        (hook_attn_scores): HookPoint()
        (hook_pattern): HookPoint()
        (hook_result): HookPoint()
        (hook_rot_k): HookPoint()
        (hook_rot_q): HookPoint()
      )
      (mlp): MLP(
        (hook_pre): HookPoint()
        (hook_post): HookPoint()
      )
      (hook_attn_in): HookPoint()
      (hook_q_input): HookPoint()
      (hook_k_input): HookPoint()
      (hook_v_input): HookPoint()
      (hook_mlp_in): HookPoint()
      (hook_attn_out): HookPoint()
      (hook_mlp_out): HookP

100%|██████████| 5/5 [00:00<00:00, 46.19it/s]

Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Num dead 0.0


tensor([0.3061, 0.0666, 0.0930,  ..., 0.0253, 0.0495, 0.1085], device='cuda:0')

In [20]:
get_freqs(
    model=lin.model, local_encoder=lin.saes["0/0_8192"], all_tokens=lin.data, layer=0, num_batches=5, act_name="mlp_out"
)

get_freqs


100%|██████████| 5/5 [00:00<00:00, 38.75it/s]

Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Starting run_with_cache
Looking for blocks.0.hook_mlp_out
Cache keys: dict_keys(['blocks.0.hook_mlp_out'])
Num dead 0.0


tensor([0.3094, 0.0635, 0.0989,  ..., 0.0226, 0.0463, 0.1076], device='cuda:0')

In [13]:
lin.saes

{'0/0_8192': AutoEncoder(),
 '1/0_8192': AutoEncoder(),
 '2/0_8192': AutoEncoder(),
 '3/0_8192': AutoEncoder(),
 '4/0_8192': AutoEncoder(),
 '5/0_8192': AutoEncoder()}

In [25]:
lin = SAELinearizer(
    model_name="pythia-70m",
    sae_names=[f"{x}/0_8192" for x in [0, 1, 2, 3, 4, 5]],
    layers=[0, 1, 2, 3, 4, 5],
    dataset_name="NeelNanda/pile-10k",
    act_name="mlp_out",
    num_batches=50,
)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Loaded pretrained model pythia-70m into HookedTransformer
Moving model to device:  cuda
Changing model dtype to torch.float16
Model device: cuda:0


Tokens shape: torch.Size([120866, 128]), dtype: torch.int64, device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
Encoder device: cuda:0
dict_keys(['0/0_8192', '1/0_8192', '2/0_8192', '3/0_8192', '4/0_8192', '5/0_8192'])


100%|██████████| 50/50 [00:01<00:00, 30.66it/s]


Num dead 0.0


100%|██████████| 50/50 [00:01<00:00, 30.79it/s]


Num dead 0.0125732421875


100%|██████████| 50/50 [00:01<00:00, 32.46it/s]


Num dead 0.0926513671875


100%|██████████| 50/50 [00:01<00:00, 29.29it/s]


Num dead 0.0218505859375


100%|██████████| 50/50 [00:01<00:00, 28.09it/s]


Num dead 0.0


100%|██████████| 50/50 [00:01<00:00, 27.63it/s]


Num dead 0.000244140625


100%|██████████| 50/50 [04:41<00:00,  5.64s/it]


In [26]:
lin.set_feature(10, "1/0_8192")

 48%|████▊     | 12/25 [00:00<00:00, 34.44it/s]

100%|██████████| 25/25 [00:00<00:00, 28.38it/s]
